pipeline{
    agent any

    stages{
        stage('Build'){
            steps{
                    echo "In Stage_01::Step_01"
                    echo "Using the parameter: " + $param_01
                
            }
        }
    }
}